# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-01 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_record_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_record',
            old_name='post',
            new_name='enable_post',
        ),
    ]
