# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-01 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170401_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_record',
            name='enable_post',
            field=models.BooleanField(default=True),
        ),
    ]
